import 'package:platform_conv/model/student.dart';

List<Student> sList = [
  Student(id: 1, name: "Alice Smith", marks: 85),
  Student(id: 2, name: "Bob Johnson", marks: 78),
  Student(id: 3, name: "Charlie Brown", marks: 92),
  Student(id: 4, name: "Diana Prince", marks: 88),
  Student(id: 5, name: "Ethan Hunt", marks: 90),
  Student(id: 6, name: "Fiona Gallagher", marks: 75),
  Student(id: 7, name: "George Lucas", marks: 82),
  Student(id: 8, name: "Hannah Montana", marks: 95),
  Student(id: 9, name: "Ian Malcolm", marks: 80),
  Student(id: 10, name: "Jessica Jones", marks: 87),
  Student(id: 11, name: "Kevin Hart", marks: 93),
  Student(id: 12, name: "Laura Croft", marks: 89),
  Student(id: 13, name: "Mike Wazowski", marks: 76),
  Student(id: 14, name: "Nina Simone", marks: 84),
  Student(id: 15, name: "Oscar Isaac", marks: 91),
  Student(id: 16, name: "Penny Lane", marks: 79),
  Student(id: 17, name: "Quinn Fabray", marks: 86),
  Student(id: 18, name: "Ryan Gosling", marks: 94),
  Student(id: 19, name: "Sarah Connor", marks: 82),
  Student(id: 20, name: "Tom Hardy", marks: 88),
  Student(id: 21, name: "Uma Thurman", marks: 77),
  Student(id: 22, name: "Vera Wang", marks: 90),
  Student(id: 23, name: "Will Smith", marks: 84),
  Student(id: 24, name: "Xena Warrior", marks: 96),
  Student(id: 25, name: "Yoda Green", marks: 81),
  Student(id: 26, name: "Zoe Saldana", marks: 89),
  Student(id: 27, name: "Alex Turner", marks: 83),
  Student(id: 28, name: "Beyoncé Knowles", marks: 95),
  Student(id: 29, name: "Chris Hemsworth", marks: 92),
  Student(id: 30, name: "Daisy Ridley", marks: 86),
  Student(id: 31, name: "Elon Musk", marks: 91),
  Student(id: 32, name: "Freya Allan", marks: 75),
  Student(id: 33, name: "Gina Carano", marks: 87),
  Student(id: 34, name: "Henry Cavill", marks: 90),
  Student(id: 35, name: "Isla Fisher", marks: 82),
  Student(id: 36, name: "Jack Black", marks: 79),
  Student(id: 37, name: "Kate Winslet", marks: 94),
  Student(id: 38, name: "Leonardo DiCaprio", marks: 88),
  Student(id: 39, name: "Mila Kunis", marks: 83),
  Student(id: 40, name: "Nathan Drake", marks: 76),
  Student(id: 41, name: "Olivia Wilde", marks: 90),
  Student(id: 42, name: "Paul Rudd", marks: 92),
  Student(id: 43, name: "Quincy Jones", marks: 85),
  Student(id: 44, name: "Rachel McAdams", marks: 78),
  Student(id: 45, name: "Sam Wilson", marks: 91),
  Student(id: 46, name: "Tina Fey", marks: 84),
  Student(id: 47, name: "Ursula K. Le Guin", marks: 95),
  Student(id: 48, name: "Vin Diesel", marks: 82),
  Student(id: 49, name: "Wanda Maximoff", marks: 87),
  Student(id: 50, name: "Xander Cage", marks: 8)
];
